# nginx proxy address - http://172.17.0.1:8200

name: duplicati
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    pull_policy: always
    container_name: duplicati-app
    restart: always
    logging: *default-logging
    networks:
      - duplicati
    ports:
      - "172.17.0.1:8200:8200"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/duplicati:/config
      - ./volumes/data/duplicati:/data
      - /:/source:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  duplicati:
    name: duplicati
    external: false
